"""One-off maintenance script (Step 2 continuation): regenerate converted/*.md
+ .metadata.json for the documents that are CURRENTLY indexed in Chroma,
using the latest ingest.py, and build a compact manifest of every file found
under docs/, converted/, and books/.

Read-only with respect to Chroma (only calls rag.list_documents(), never
upserts/deletes). Writes only under converted/. Never deletes or modifies
anything under docs/ or books/.

Usage (PowerShell, from the project venv):
    .\\venv\\Scripts\\python.exe scripts\\normalize_existing_documents.py
"""
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout.reconfigure(encoding="utf-8")

import ingest  # noqa: E402
import rag  # noqa: E402  (read-only: only rag.list_documents() is called)

DOCS_DIR = "./docs"
CONVERTED_DIR = "./converted"
BOOKS_DIR = "./books"


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def normalize_indexed_document(document_id: str, source_filename: str) -> dict:
    """Finds the original upload for an already-indexed document_id and
    regenerates its converted/*.md + .metadata.json from scratch using the
    current ingest.py. Returns a small status dict for the manifest."""
    candidates = [f for f in os.listdir(DOCS_DIR) if f.startswith(document_id + ".")]
    if not candidates:
        return {"normalized": False, "reason": "no matching docs/ file found"}
    original_name = candidates[0]
    original_path = os.path.join(DOCS_DIR, original_name)
    ext = os.path.splitext(original_name)[1].lower()

    with open(original_path, "rb") as f:
        raw = f.read()
    import io
    try:
        normalized = ingest.normalize_document(source_filename, io.BytesIO(raw), ext)
    except Exception as e:
        return {"normalized": False, "reason": f"normalize_document failed: {e}"}

    md_path, _meta_path = ingest.paths_for(document_id)
    metadata = {
        "document_id": document_id,
        "original_filename": source_filename,
        "source_file_type": ext.lstrip("."),
        "original_upload_path": original_path,
        "normalized_md_path": md_path,
        "created_at": ingest.now_iso(),
        "normalization_version": ingest.NORMALIZATION_VERSION,
        **normalized["meta"],
        "note": "regenerated by scripts/normalize_existing_documents.py; Chroma NOT touched",
    }
    ingest.write_normalized(document_id, normalized["markdown_text"], metadata)
    return {
        "normalized": True,
        "normalized_md_path": md_path,
        "structure_confidence": normalized["meta"]["structure_confidence"],
        "heading_count": normalized["meta"]["heading_count"],
        "extraction_quality_warning": normalized["meta"]["extraction_quality_warning"],
    }


def main():
    indexed = rag.list_documents(user_id=None)
    indexed_by_id = {d["document_id"]: d["source"] for d in indexed}
    print(f"Currently indexed in Chroma: {len(indexed)} document(s)")
    for d in indexed:
        print(" -", d["document_id"], "->", d["source"])

    print("\nRegenerating converted/*.md + metadata for indexed documents (Chroma untouched)...")
    normalize_results = {}
    for doc_id, source in indexed_by_id.items():
        print(f"  {doc_id} ({source}) ...", end=" ")
        result = normalize_indexed_document(doc_id, source)
        normalize_results[doc_id] = result
        print("OK" if result.get("normalized") else f"SKIPPED ({result.get('reason')})")

    # ---- Build the full manifest over docs/, converted/, books/ ----
    manifest = {"generated_at": ingest.now_iso(), "entries": []}

    hash_to_files = {}
    for fname in sorted(os.listdir(DOCS_DIR)):
        path = os.path.join(DOCS_DIR, fname)
        if not os.path.isfile(path):
            continue
        try:
            h = sha256_of(path)
        except Exception:
            h = None
        hash_to_files.setdefault(h, []).append(fname)

    for fname in sorted(os.listdir(DOCS_DIR)):
        path = os.path.join(DOCS_DIR, fname)
        if not os.path.isfile(path) or fname == ".gitkeep":
            continue
        stem, ext = os.path.splitext(fname)
        is_uuid_named = len(stem) == 32 and all(c in "0123456789abcdef" for c in stem)
        document_id = stem if is_uuid_named else None
        indexed_source = indexed_by_id.get(document_id) if document_id else None
        h = sha256_of(path)
        dupes = [f for f in hash_to_files.get(h, []) if f != fname]
        md_path, meta_path = (ingest.paths_for(document_id) if document_id else (None, None))
        has_md = bool(md_path and os.path.exists(md_path))
        has_meta = bool(meta_path and os.path.exists(meta_path))

        if document_id and document_id in indexed_by_id:
            action = "already indexed; converted/*.md regenerated by this script" if normalize_results.get(document_id, {}).get("normalized") else "already indexed; converted/*.md NOT regenerated (see reason)"
        elif is_uuid_named:
            action = "orphaned upload (uuid-named, not referenced by current Chroma data) -- safe to leave; candidate for manual cleanup later, not deleted"
        else:
            action = "manually-placed source file (not uuid-named, never went through the app upload flow) -- candidate source material, no document_id"

        suspected_relation = None
        if dupes:
            suspected_relation = f"byte-identical to: {', '.join(dupes)}"
        elif "determaind" in fname.lower():
            suspected_relation = "related to the Sapolsky 'Determined' book test corpus (see books/determaind.epub, converted/determaind.md)"
        elif "cosmeticorexia" in fname.lower():
            suspected_relation = "related to the cosmeticorexia test document"

        manifest["entries"].append({
            "filename": fname,
            "path": path,
            "size_bytes": os.path.getsize(path),
            "sha256": h,
            "document_id": document_id,
            "currently_indexed": document_id in indexed_by_id if document_id else False,
            "indexed_source_name": indexed_source,
            "converted_md_exists": has_md,
            "converted_metadata_exists": has_meta,
            "suspected_source_relation": suspected_relation,
            "recommended_next_action": action,
        })

    # Legacy pre-Step2 converted/ artifacts (not document_id-named)
    for fname in sorted(os.listdir(CONVERTED_DIR)):
        path = os.path.join(CONVERTED_DIR, fname)
        if not os.path.isfile(path):
            continue
        stem = fname.split(".")[0]
        if len(stem) == 32 and all(c in "0123456789abcdef" for c in stem):
            continue  # already covered above via the docs/ entry
        manifest["entries"].append({
            "filename": fname,
            "path": path,
            "size_bytes": os.path.getsize(path),
            "sha256": sha256_of(path),
            "document_id": None,
            "currently_indexed": False,
            "indexed_source_name": None,
            "converted_md_exists": None,
            "converted_metadata_exists": None,
            "suspected_source_relation": "pre-Step-2 legacy conversion artifact (not produced by ingest.py; richer chapter/section structure from an external epub->markdown tool)" if fname.endswith(".md") else "pre-Step-2 legacy plain-text conversion artifact",
            "recommended_next_action": "keep as reference; if/when 'Determined' is re-ingested for structured Chroma migration, prefer re-deriving structure from this richer .md (or books/determaind.epub) over the flat indexed .txt, which has no headers to recover",
        })

    for fname in sorted(os.listdir(BOOKS_DIR)):
        path = os.path.join(BOOKS_DIR, fname)
        if not os.path.isfile(path):
            continue
        manifest["entries"].append({
            "filename": fname,
            "path": path,
            "size_bytes": os.path.getsize(path),
            "sha256": sha256_of(path),
            "document_id": None,
            "currently_indexed": False,
            "indexed_source_name": None,
            "converted_md_exists": None,
            "converted_metadata_exists": None,
            "suspected_source_relation": "original source book (epub), not processed by ingest.py (no epub support implemented)",
            "recommended_next_action": "no action; available as the highest-fidelity source if epub support is added later",
        })

    manifest_path = os.path.join(CONVERTED_DIR, "document_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    print(f"\nManifest written: {manifest_path} ({len(manifest['entries'])} entries)")


if __name__ == "__main__":
    main()
